DigitizingProjectCore/Areas/Admin/Controllers/CategoryServiceController.cs
using DigitizingProjectCore.Areas.Admin.Dto;
using DigitizingProjectCore.Data;
using DigitizingProjectCore.Services.CategoryServiceService;
using Microsoft.AspNetCore.Mvc;


namespace DigitizingProjectCore.Areas.Admin.Controllers
{
    public class CategoryServiceController : AdminBaseController
    {
        private readonly ICategoryServiceService  _categoryServiceService;
       
        public CategoryServiceController(ICategoryServiceService categoryServiceService)
        {
            _categoryServiceService = categoryServiceService;           
        }
        [HttpGet]
        public async Task<IActionResult> Index(string? key)
        {
            var _Categories = await _categoryServiceService.GetAll(key);
            return View(_Categories);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(CreateUpdateCategoryDto dto)
        {
            if (ModelState.IsValid)
            {
                await  _categoryServiceService.Create(dto);
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", await _categoryServiceService.GetAll()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Add", dto) });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var _category = await _categoryServiceService.GetById(id);
            return View(_category);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CreateUpdateCategoryDto dto)
        {
            if (ModelState.IsValid)
            {
                await _categoryServiceService.Update(dto);
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", await _categoryServiceService.GetAll()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", dto) });
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id) {
            var _category = await _categoryServiceService.GetById(id);
            return View(_category);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(CreateUpdateCategoryDto dto)
        {
            await _categoryServiceService.Delete(dto.Id);
            return Json(new { html = Helper.RenderRazorViewToString(this, "_ViewAll", await _categoryServiceService.GetAll()) });
        }
        
    }
}

DigitizingProjectCore/Areas/Admin/Views/CategoryService/Add.cshtml
@model DigitizingProjectCore.Areas.Admin.Dto.CreateUpdateCategoryDto
@{
    Layout = null;
}
<form asp-controller="CategoryService" asp-action="Add" method="POST" onsubmit="return jQueryAjaxPost(this);">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="nameEn">Name (English)</label>
                <input type="text" class="form-control" id="nameEn" asp-for="NameEn">
                <span asp-validation-for="NameEn" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="nameAr">Name (Arabic)</label>
                <input type="text" class="form-control" id="nameAr" asp-for="NameAr">
                <span asp-validation-for="NameAr" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="active">Active</label>
                <input type="checkbox" id="active" checked asp-for="IsActive">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="sortId">#Sort Id</label>
                <input type="number" class="form-control" id="sortId" asp-for="SortId">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <button type="submit" class="btn btn-primary btn-create">Create</button>
        </div>
        <div class="col-md-2">
            <input type="reset" class="btn" value="Rest">
        </div>
    </div>
</form>

DigitizingProjectCore/Areas/Admin/Views/CategoryService/Delete.cshtml
@model DigitizingProjectCore.Areas.Admin.Dto.CreateUpdateCategoryDto
@{
    Layout = null;
}
<form asp-action="Delete" asp-controller="CategoryService" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
    <input type="hidden" asp-for="Id" />
    <label>Are You Sure?</label><br />
    <input type="submit" value="Delete" class="btn btn-danger">
</form>

DigitizingProjectCore/Areas/Admin/Views/CategoryService/Edit.cshtml
@model DigitizingProjectCore.Areas.Admin.Dto.CreateUpdateCategoryDto
@{
    Layout = null;
}
<form asp-controller="CategoryService" asp-action="Edit" onsubmit="return jQueryAjaxPost(this);" method="POST">
    <input type="hidden" asp-for="Id">
    <div class="form-group">
        <label for="NameEn">Name (English)</label>
        <input type="text" class="form-control" id="NameEn" asp-for="NameEn">
        <span asp-validation-for="NameEn" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="NameAr">Name (Arabic)</label>
        <input type="text" class="form-control" id="NameAr" asp-for="NameAr">
        <span asp-validation-for="NameEn" class="text-danger"></span>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="active">Active</label>
                @if (Model.IsActive)
                {
                    <input type="checkbox" id="active" checked asp-for="IsActive">
                }
                else
                {
                    <input type="checkbox" id="active" asp-for="IsActive">
                }
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="sortId">#Sort Id</label>
                <input type="number" class="form-control" id="sortId" asp-for="SortId">
            </div>
        </div>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-warning btn-create">Edit</button>
        <input type="reset" class="btn" value="Rest">
    </div>
</form>

DigitizingProjectCore/Areas/Admin/Views/CategoryService/Index.cshtml
@model List<CategoryViewModel>
@section css{
    <style>
        .table-responsive {
            overflow-x: hidden;
        }
    </style>
    <link rel="stylesheet" href="sweetalert2.min.css">
}
<div class="panel panel-default">
    <div class="panel-heading">
        <form class="form-inline" asp-controller="CategoryService" asp-action="Index" method="GET">
            <div class="form-group">
                <input type="text" placeholder="search ..." name="key" class="form-control"/>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
            </div>
        </form>
    </div>
    <div class="panel-body" id="view-all">
        @await Html.PartialAsync("_ViewAll", Model)
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="form-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>
@section scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript">
        $(document).ready(function () {
            $("#tbllist").DataTable({
                "bFilter": false,
                "bDestroy": true,
                "bSort": false,
                "bStateSave": true,
            });
        })
    </script>

}

DigitizingProjectCore/Areas/Admin/Views/CategoryService/_ViewAll.cshtml
@model List<CategoryViewModel>
<div class="table-responsive">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-6">
                    <h2>Service Categories</h2>
                </div>
                <div class="col-sm-6 text-right">
                    <a class="btn btn-success" onclick="showInPopup('@Url.Action("Add" , "CategoryService" ,null ,Context.Request.Scheme)' , 'Add Category Service');">Add Category Service</a>
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover" id="tbllist">
            <thead>
                <tr>
                    <th>Name (English)</th>
                    <th>Name (Arabic)</th>
                    <th>Active</th>
                    <th>Created Date</th>
                    <th width="15%"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.NameEn</td>
                        <td>@item.NameAr</td>
                        @if (item.IsActive)
                        {
                            <td><input type="checkbox" checked></td>
                        }
                        else
                        {
                            <td><input type="checkbox"></td>
                        }
                        <td>@item.Created_At.ToString("dddd, dd MMMM yyyy")</td>
                        <td>
                            <a class='btn PopUp btn-xs btn-success' onclick="showInPopup('/Admin/Home/Links?route=/Service/Index&id=@item.Id')"><i class='glyphicon glyphicon-link'></i></a>
                            <a class='btn btn-xs btn-info PopUp' onclick="showInPopup('@Url.Action("Edit" , "CategoryService" ,new{id = item.Id} ,Context.Request.Scheme)' , 'Edit Category Service');"><i class='glyphicon glyphicon-edit'></i></a>
                            <a class="btn btn-xs btn-danger PopUp" onclick="showInPopup('@Url.Action("Delete" , "CategoryService" ,new{id = item.Id} ,Context.Request.Scheme)' , 'Delete Category Service');"><i class='glyphicon glyphicon-trash'></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>