DigitizingProjectCore/Models/PhotoGallery.cs
namespace DigitizingProjectCore.Models
{
    public class PhotoGallery : BaseEntity
    {
        public int Id { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public string MainImageName { get; set; }
        public int SortId { get; set; }
        public string SummaryEn { get; set; }
        public string SummaryAr { get; set; }
        public string ImagesName { get; set; }
    }
}

DigitizingProjectCore/Areas/Admin/Controllers/PhotoGalleryController.cs
using DigitizingProjectCore.Areas.Admin.Dto;
using DigitizingProjectCore.Data;
using DigitizingProjectCore.Services.CategoryServiceService;
using DigitizingProjectCore.Services.PhotoGalleryService;
using Humanizer;
using Microsoft.AspNetCore.Mvc;

namespace DigitizingProjectCore.Areas.Admin.Controllers
{
    public class PhotoGalleryController : AdminBaseController
    {
        private readonly IPhotoGalleryService _photoGalleryService;

        public PhotoGalleryController(IPhotoGalleryService photoGalleryService)
        {
            _photoGalleryService = photoGalleryService;
        }
        [HttpGet]
        public async Task<IActionResult> Index(string? key , bool? isActive )
        {
            var _Categories = await _photoGalleryService.GetAll(key , isActive);
            return View(_Categories);
        }
        [HttpPost]
        public async Task<ActionResult> Search(string term = "")
        {
            return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", await _photoGalleryService.Search(term)) });
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(CreateUpdatePhotoGalleryDto dto)
        {
            if (ModelState.IsValid)
            {
                await _photoGalleryService.Create(dto);
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", await _photoGalleryService.GetAll()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Add", dto) });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var _category = await _photoGalleryService.GetById(id);
            return View(_category);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CreateUpdatePhotoGalleryDto dto)
        {
            if (ModelState.IsValid)
            {
                await _photoGalleryService.Update(dto);
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", await _photoGalleryService.GetAll()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", dto) });
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var _PhotoGallery = await _photoGalleryService.GetById(id);
            return View(_PhotoGallery);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(CreateUpdatePhotoGalleryDto dto)
        {
            await _photoGalleryService.Delete(dto.Id);
            return Json(new { html = Helper.RenderRazorViewToString(this, "_ViewAll", await _photoGalleryService.GetAll()) });
        }
        [HttpPost]
        public async Task<IActionResult> DeleteImage(int id, string imageNames) {
            var _PhotoGallery = await _photoGalleryService.GetById(id);
            int result = await _photoGalleryService.DeleteImage(id, imageNames);
            if (result != 0) {
                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", _PhotoGallery) });
            }
            return Json(new { html = Helper.RenderRazorViewToString(this, "_ViewAll", await _photoGalleryService.GetAll()) });
        }
    }
}

DigitizingProjectCore/Controllers/PhotoGalleryController.cs
using DigitizingProjectCore.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DigitizingProjectCore.Controllers
{
    public class PhotoGalleryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public PhotoGalleryController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var newsQuery = await _context.PhotoGalleries.Where(x => x.IsDelete == false && x.IsActive == true).OrderByDescending(x => x.Created_At).ToListAsync();
            return View(newsQuery);
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var newsQuery = await _context.PhotoGalleries.Where(x => x.IsDelete == false && x.IsActive == true && x.Id == id).FirstOrDefaultAsync();
            return View(newsQuery);
        }
    }
}

DigitizingProjectCore/Areas/Admin/Views/PhotoGallery/Add.cshtml
@model DigitizingProjectCore.Areas.Admin.Dto.CreateUpdatePhotoGalleryDto
@{
    Layout = null;
}
@section css{
    <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />
}
<form asp-controller="PhotoGallery" asp-action="Add" method="POST" enctype="multipart/form-data" onsubmit="return jQueryAjaxPost(this);">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="nameAr">Name (Arabic)</label>
                <input type="text" class="form-control" id="nameAr" asp-for="NameAr">
                <span asp-validation-for="NameAr" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="nameEn">Name (English)</label>
                <input type="text" class="form-control" id="nameEn" asp-for="NameEn">
                <span asp-validation-for="NameEn" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 form-group">
            <label for="summaryAr">Summary (Arabic)</label>
            <textarea type="text" class="form-control" id="summaryAr" cols="20" rows="3" asp-for="SummaryAr"></textarea>
            <span asp-validation-for="SummaryAr" class="text-danger"></span>
        </div>
        <div class="col-md-6 form-group">
            <label for="summaryEn">Summary (English)</label>
            <textarea type="text" class="form-control" id="summaryEn" cols="20" rows="3" asp-for="SummaryEn"></textarea>
            <span asp-validation-for="SummaryEn" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 form-group">
            <label for="mainImage">Main Image</label>
            <input type="file" class="form-control" id="mainImage" asp-for="MainImage">
        </div>
        <div class="col-md-6 form-group">
            <label for="sort">Sort(#)</label>
            <input type="number" class="form-control" placeholder="Enter date" id="sort" asp-for="SortId">
        </div>
    </div>
    <div class="form-group">
        <label for="images">Images</label>
        <div id="uploadImages" style="width:400px;height:400px;line-height:400px;border:1px solid #000000;text-align:center" class="dropzone">
            <input type="file" multiple class="form-control" id="images" asp-for="Images">
        </div>

    </div>
    <div class="form-group">
        <label for="active">Active</label>
        <input type="checkbox" id="active" checked asp-for="IsActive">
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-create">Create</button>
        <input type="reset" class="btn" value="Rest">
    </div>

</form>
@section scripts{
    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
}

DigitizingProjectCore/Areas/Admin/Views/PhotoGallery/Delete.cshtml
@model DigitizingProjectCore.Areas.Admin.Dto.CreateUpdatePhotoGalleryDto
@{
    Layout = null;
}
<form asp-action="Delete" asp-controller="PhotoGallery" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
    <input type="hidden" asp-for="Id" />
    <label>Are You Sure?</label><br />
    <input type="submit" value="Delete" class="btn btn-danger">
</form>

DigitizingProjectCore/Areas/Admin/Views/PhotoGallery/Edit.cshtml
@model DigitizingProjectCore.Areas.Admin.Dto.CreateUpdatePhotoGalleryDto
@{
    Layout = null;
}

<form asp-controller="PhotoGallery" asp-action="Edit" method="POST" enctype="multipart/form-data" onsubmit="return jQueryAjaxPost(this);">
    <input type="hidden" asp-for="Id" />
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="nameAr">Name (Arabic)</label>
                <input type="text" class="form-control" id="nameAr" asp-for="NameAr">
                <span asp-validation-for="NameAr" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="nameEn">Name (English)</label>
                <input type="text" class="form-control" id="nameEn" asp-for="NameEn">
                <span asp-validation-for="NameEn" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 form-group">
            <label for="summaryAr">Summary (Arabic)</label>
            <textarea type="text" class="form-control" id="summaryAr" cols="20" rows="3" asp-for="SummaryAr"></textarea>
            <span asp-validation-for="SummaryAr" class="text-danger"></span>
        </div>
        <div class="col-md-6 form-group">
            <label for="summaryEn">Summary (English)</label>
            <textarea type="text" class="form-control" id="summaryEn" cols="20" rows="3" asp-for="SummaryEn"></textarea>
            <span asp-validation-for="SummaryEn" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 form-group">
            <label for="mainImage">Main Image</label>
            <img src="/Images/@Model.MainImageName" alt="@(Model.NameEn)" width="250" height="250">
            <input type="file" class="form-control" id="mainImage" asp-for="MainImage">
        </div>
        <div class="col-md-6 form-group">
            <label for="sort">Sort(#)</label>
            <input type="number" class="form-control" placeholder="Enter date" id="sort" asp-for="SortId">
        </div>
    </div>
    <div class="form-group">
        <label for="images">Images</label>
        @if (Model.ImagesName != null)
        {
            <div class="row imgGallery">
                @foreach (var imageName in Model.ImagesName.Split(','))
                {
                    if (imageName != "")
                    {
                        <div class="col-sm-2">
                            <img fname="@imageName" src="/Images/@imageName" width="100" height="100">
                            <button data-id="@Model.Id" type="button" id="btnDeleteImage" class="btn btn-xs btn-danger">
                                <i class="fa fa-trash"></i>
                            </button>
                        </div>
                    }
                }
            </div>
        }
        <input type="file" multiple class="form-control" id="images" asp-for="Images">
    </div>
    <div class="form-group">
        <label for="active">Active</label>
        <input type="checkbox" id="active" checked asp-for="IsActive">
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-warning">Edit</button>
        <input type="reset" class="btn" value="Rest">
    </div>

</form>

DigitizingProjectCore/Areas/Admin/Views/PhotoGallery/Index.cshtml
@model List<PhotoGalleryViewModel>
@section css{
    <style>
        .table-responsive {
            overflow-x: hidden;
        }
    </style>
    <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />
}
<div class="panel panel-default">
    <div class="panel-heading">
        <form class="form-inline" asp-controller="PhotoGallery" asp-action="Index" method="GET">
            <div class="form-group">
                <input type="text" placeholder="search ..." name="key" class="form-control" />
            </div>
            <div class="form-group">
                <select name="isActive" class="form-control">
                    <option value="null">Is Active</option>
                    <option value="true">Active</option>
                    <option value="false">Not Active</option>
                </select>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
            </div>
        </form>
    </div>
    <div class="panel-body" id="view-all">
        @await Html.PartialAsync("_ViewAll", Model)
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="form-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>
@section scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript">
        $(document).ready(function () {
            $("#tbllist").DataTable({
                "bFilter": false,
                "bDestroy": true,
                "bSort": false,
                "bStateSave": true,
            });
        })
    </script>
    <script type="text/javascript">
        $("#btnDeleteImage").click(function () {
            alert("The paragraph was clicked.");
        });
    </script>
}

DigitizingProjectCore/Areas/Admin/Views/PhotoGallery/_ViewAll.cshtml
@model List<PhotoGalleryViewModel>
<div class="table-responsive">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-6">
                    <h2>Photo Galleries</h2>
                </div>
                <div class="col-sm-6 text-right">
                    <a class="btn btn-success" onclick="showInPopup('@Url.Action("Add" , "PhotoGallery" ,null ,Context.Request.Scheme)' , 'Add Photo Gallery');">Add Photo Gallery</a>
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover" id="tbllist">
            <thead>
                <tr>
                    <th>Name (English)</th>
                    <th>Name (Arabic)</th>
                    <th>Active</th>
                    <th>Created Date</th>
                    <th width="15%"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.NameEn</td>
                        <td>@item.NameAr</td>
                        @if (item.IsActive)
                        {
                            <td><input type="checkbox" checked></td>
                        }
                        else
                        {
                            <td><input type="checkbox"></td>
                        }
                        <td>@item.Created_At.ToString("dddd, dd MMMM yyyy")</td>
                        <td>
                            <a href="#" class='btn PopUp btn-xs btn-success'><i class='glyphicon glyphicon-link'></i></a>
                            <a class='btn btn-xs btn-info PopUp' onclick="showInPopup('@Url.Action("Edit" , "PhotoGallery" ,new{id = item.Id} ,Context.Request.Scheme)' , 'Edit Category Service');"><i class='glyphicon glyphicon-edit'></i></a>
                            <a class="btn btn-xs btn-danger PopUp" onclick="showInPopup('@Url.Action("Delete" , "PhotoGallery" ,new{id = item.Id} ,Context.Request.Scheme)' , 'Delete Category Service');"><i class='glyphicon glyphicon-trash'></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>