DigitizingProjectCore/Models/Distributor.cs
namespace DigitizingProjectCore.Models
{
    public class Distributor : BaseEntity
    {
        public int Id { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
        public string AddressAr { get; set; }
        public string AddressEn { get; set; }
        public string Phone { get; set; }
        public int? CityId { get; set; }
        public City City { get; set; }
    }
}

DigitizingProjectCore/Areas/Admin/Controllers/DistributorController.cs
using AutoMapper;
using DigitizingProjectCore.Areas.Admin.Dto;
using DigitizingProjectCore.Data;
using DigitizingProjectCore.Services.DistributorService;
using Microsoft.AspNetCore.Mvc;

namespace DigitizingProjectCore.Areas.Admin.Controllers
{
    public class DistributorController : AdminBaseController
    {
        private readonly IDistributorService _distributorService;
        private readonly IMapper _mapper;
        public DistributorController(IDistributorService distributorService , IMapper mapper)
        {
            _distributorService = distributorService;
            _mapper = mapper;
        }
        [HttpGet]
        public async Task<IActionResult> Index(string? key , int? cityId , bool? isActive)
        {
            var _Distributors = await _distributorService.GetAll(key , cityId , isActive);
            return View(_Distributors);
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var _CreateUpdateDistributor = await _distributorService.InjectCities();
            return View(_CreateUpdateDistributor);
        }
        [HttpPost]
        public async Task<IActionResult> Add(CreateUpdateDistributorDto dto)
        {
            if (ModelState.IsValid)
            {
                await _distributorService.Create(dto);
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", await _distributorService.GetAll()) });
            }

            var _CreateUpdateDistributor = await _distributorService.InjectCities();
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Add", _CreateUpdateDistributor) });
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var _Distributor = await _distributorService.GetById(id);
            var _AddDistributorWithCity = await _distributorService.InjectCities();
            _AddDistributorWithCity = _mapper.Map(_Distributor, _AddDistributorWithCity);
            return View(_AddDistributorWithCity);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CreateUpdateDistributorDto dto)
        {
            if (ModelState.IsValid)
            {
                await _distributorService.Update(dto);
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", await _distributorService.GetAll()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", dto) });
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var _Distributor = await _distributorService.GetById(id);
            var dto = _mapper.Map<CreateUpdateDistributorDto>(_Distributor);
            return View(dto);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(CreateUpdateDistributorDto dto)
        {
            await _distributorService.Delete(dto.Id);
            return Json(new { html = Helper.RenderRazorViewToString(this, "_ViewAll", await _distributorService.GetAll()) });
        }
    }
}

DigitizingProjectCore/Controllers/DistributorController.cs
using DigitizingProjectCore.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DigitizingProjectCore.Controllers
{
    public class DistributorController : Controller
    {
        private readonly ApplicationDbContext _context;
        public DistributorController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var distributors = await _context.Distributors.Where(x => x.IsDelete == false && x.IsActive == true).Include(x => x.City).ToListAsync();
            return View(distributors);
        }
    }
}

DigitizingProjectCore/Areas/Admin/Views/Distributor/Add.cshtml
@model DigitizingProjectCore.Areas.Admin.Dto.AddDistibutorWithCity
@{
    Layout = null;
}

<form asp-controller="Distributor" asp-action="Add" method="POST" enctype="multipart/form-data" onsubmit="return jQueryAjaxPost(this);">
    <div class="row">
        <div class="col-md-6 form-group">
            <label for="nameAr">Name (Arabic)</label>
            <input type="text" class="form-control" id="nameAr" asp-for="NameAr">
            <span asp-validation-for="NameAr" class="text-danger"></span>
        </div>
        <div class="col-md-6 form-group">
            <label for="nameEn">Name (English)</label>
            <input type="text" class="form-control" id="nameEn" asp-for="NameEn">
            <span asp-validation-for="NameEn" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 form-group">
            <label for="addressAr">Address (Arabic)</label>
            <textarea type="text" class="form-control" id="addressAr" cols="20" rows="3" asp-for="AddressAr"></textarea>
            <span asp-validation-for="AddressAr" class="text-danger"></span>
        </div>
        <div class="col-md-6 form-group">
            <label for="addressEn">Address (English)</label>
            <textarea type="text" class="form-control" id="addressEn" cols="20" rows="3" asp-for="AddressEn"></textarea>
            <span asp-validation-for="AddressEn" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 form-group">
            <label for="city">City</label>
            <select class="form-control" id="city" asp-for="CityId" asp-items="Model._Cities"></select>
            <span asp-validation-for="CityId" class="text-danger"></span>
        </div>
        <div class="col-md-6 form-group">
            <label for="sort">Sort(#)</label>
            <input type="text" class="form-control" id="sort" asp-for="SortId">
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 form-group">
            <label for="active">Active</label>
            <input type="checkbox" id="active" checked asp-for="IsActive">
        </div>
        <div class="col-md-6 form-group">
            <label for="phone">Phone</label>
            <input type="text" class="form-control" id="phone" asp-for="Phone">
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>
    </div>
    
    <input type="submit" class="btn btn-primary" value="Create" />
</form>

DigitizingProjectCore/Areas/Admin/Views/Distributor/Delete.cshtml
@model DigitizingProjectCore.Areas.Admin.Dto.CreateUpdateDistributorDto
@{
    Layout = null;
}
<form asp-action="Delete" asp-controller="Distributor" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
    <input type="hidden" asp-for="Id" />
    <label>Are You Sure?</label><br />
    <input type="submit" value="Delete" class="btn btn-danger">
</form>

DigitizingProjectCore/Areas/Admin/Views/Distributor/Edit.cshtml
@model DigitizingProjectCore.Areas.Admin.Dto.AddDistibutorWithCity
@{
    Layout = null;
}

<form asp-controller="Distributor" asp-action="Edit" method="POST" enctype="multipart/form-data" onsubmit="return jQueryAjaxPost(this);">
    <input type="hidden" asp-for="Id">
    <div class="row">
        <div class="col-md-6 form-group">
            <label for="nameAr">Name (Arabic)</label>
            <input type="text" class="form-control" id="nameAr" asp-for="NameAr">
        </div>
        <div class="col-md-6 form-group">
            <label for="nameEn">Name (English)</label>
            <input type="text" class="form-control" id="nameEn" asp-for="NameEn">
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 form-group">
            <label for="addressAr">Address (Arabic)</label>
            <textarea type="text" class="form-control" id="addressAr" cols="20" rows="3" asp-for="AddressAr"></textarea>
        </div>
        <div class="col-md-6 form-group">
            <label for="addressEn">Address (English)</label>
            <textarea type="text" class="form-control" id="addressEn" cols="20" rows="3" asp-for="AddressEn"></textarea>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 form-group">
            <label for="city">City</label>
            <select class="form-control" id="city" asp-for="CityId" asp-items="Model._Cities"></select>
        </div>
        <div class="col-md-6 form-group">
            <label for="sort">Sort(#)</label>
            <input type="text" class="form-control" id="sort" asp-for="SortId">
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 form-group">
            <label for="active">Active</label>
            <input type="checkbox" id="active" checked asp-for="IsActive">
        </div>
        <div class="col-md-6 form-group">
            <label for="phone">Phone</label>
            <input type="text" class="form-control" id="phone" asp-for="Phone">
        </div>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-warning btn-create">Edit</button>
        <input type="reset" class="btn" value="Rest">
    </div>
</form>

DigitizingProjectCore/Areas/Admin/Views/Distributor/Index.cshtml
@using DigitizingProjectCore.Data;
@model List<DigitizingProjectCore.Areas.Admin.ViewModel.DistributorViewModel>
@inject ApplicationDbContext _context;
@{
    var cities = _context.Cities.Where(x => x.IsDelete == false && x.IsActive == true).ToList();
}
@section css{
    <style>
        .table-responsive {
            overflow-x: hidden;
        }
    </style>
}
<div class="panel panel-default">
    <div class="panel-heading">
        <form class="form-inline" asp-controller="Distributor" asp-action="Index" method="GET" >
            <div class="form-group">
                <input type="text" placeholder="search ..." name="key" class="form-control" />
            </div>
            <div class="form-group">
                <select name="cityId" class="form-control">
                    <option value="null">Any City</option>
                    @foreach (var city in cities)
                    {
                        <option value="@city.Id">@city.NameEn</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <select name="isActive" class="form-control">
                    <option value="null">Is Active</option>
                    <option value="true">Active</option>
                    <option value="false">Not Active</option>
                </select>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
            </div>
        </form>
    </div>
    <div class="panel-body" id="view-all">
        @await Html.PartialAsync("_ViewAll", Model)
    </div>
</div>
<div class="modal" tabindex="-1" role="dialog" id="form-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>
@section scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript">
        $(document).ready(function () {
            $("#tbllist").DataTable({
                "bFilter": false,
                "bDestroy": true,
                "bSort": false,
                "bStateSave": true,
            });
        })
    </script>
}

DigitizingProjectCore/Areas/Admin/Views/Distributor/_ViewAll.cshtml
@model List<DigitizingProjectCore.Areas.Admin.ViewModel.DistributorViewModel>
<div class="table-responsive">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-6">
                    <h2>
                        Manage Distributors
                    </h2>
                </div>
                <div class="col-sm-6 text-right">
                    <a class="btn btn-success" onclick="showInPopup('@Url.Action("Add" , "Distributor" ,null ,Context.Request.Scheme)' , 'Add Distributor');">Add Distributor</a>
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover" id="tbllist">
            <thead>
                <tr>
                    <th>Name (English)</th>
                    <th>City</th>
                    <th>Address (English)</th>
                    <th>Phone</th>
                    <th>Is Active</th>
                    <th>Created Date</th>
                    <th width="15%"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.NameEn</td>
                        <td>@((item.City.IsActive == true && item.City.IsDelete == false) ? @item.City.NameEn : "UNKNOWN")</td>
                        <td>@item.AddressEn</td>
                        <td>@item.Phone</td>

                        @if (item.IsActive)
                        {
                            <td><input type="checkbox" checked></td>
                        }
                        else
                        {
                            <td><input type="checkbox"></td>
                        }

                        <td>@item.Created_At.ToString("dddd, dd MMMM yyyy")</td>
                        <td>
                            <a class='btn btn-xs btn-info PopUp' onclick="showInPopup('@Url.Action("Edit" , "Distributor" ,new{id = item.Id} ,Context.Request.Scheme)' , 'Edit Distributor');"><i class='glyphicon glyphicon-edit'></i></a>
                            <a class="btn btn-xs btn-danger PopUp" onclick="showInPopup('@Url.Action("Delete" , "Distributor" ,new{id = item.Id} ,Context.Request.Scheme)' , 'Delete Distributor');"><i class='glyphicon glyphicon-trash'></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>